In [1]:
import torch

In [5]:
array = torch.tensor([7, 4, 3, 2, 6])
print(array)
print(array.dtype)
print(array.type())

tensor([7, 4, 3, 2, 6])
torch.int64
torch.LongTensor


In [6]:
array = torch.tensor([7.1, 4.6, 3.8, 2.0, 6])
print(array)
print(array.dtype)
print(array.type())

tensor([7.1000, 4.6000, 3.8000, 2.0000, 6.0000])
torch.float32
torch.FloatTensor


In [7]:
array = torch.FloatTensor([7, 4, 3, 2, 6])
print(array)
print(array.dtype)
print(array.type())

tensor([7., 4., 3., 2., 6.])
torch.float32
torch.FloatTensor


In [8]:
array = torch.tensor([7, 4, 3, 2, 6])

array = array.type(torch.FloatTensor)
print(array)
print(array.dtype)
print(array.type())

tensor([7., 4., 3., 2., 6.])
torch.float32
torch.FloatTensor


In [18]:
v = torch.tensor([7, 4, 3, 2, 6])
v_column = v.view(5,1)
#array = v.view(-1,1)
v_column

tensor([[7],
        [4],
        [3],
        [2],
        [6]])

In [28]:
#numpy to tensor

import numpy as np

numpy_array = np.array([0.0, 1.0, 2.0, 3.0, 4.0])

torch_tensor = torch.from_numpy(numpy_array)



back_to_numpy = torch_tensor.numpy()

torch_tensor = torch.tensor([1.0, 1.0, 2.0, 3.0, 4.0])

print(torch_tensor)
print(back_to_numpy)


tensor([1., 1., 2., 3., 4.])
[0. 1. 2. 3. 4.]


In [31]:
#pandas to tensor

import pandas as pd 

pandas_series = pd.Series([0.1, 2, 0.3, 10.1])

pandas_to_torch = torch.from_numpy(pandas_series.values)#要先轉成numpy array才能用torch.from_numpy


print(pandas_to_torch)


tensor([ 0.1000,  2.0000,  0.3000, 10.1000], dtype=torch.float64)


In [32]:
#tensor to list

this_tensor = torch.tensor([0,1,2,3])

torch_to_list = this_tensor.tolist()

torch_to_list

[0, 1, 2, 3]

In [34]:
#tensor

this_tensor = torch.tensor([0,1,2,3])

this_tensor[0].item() #get value

0

In [45]:
c = torch.tensor([20,1,2,3,4])
c[0] = 100

c[3:5] = torch.tensor([5,6]) * 2

d = c[1:4]

c

tensor([100,   1,   2,  10,  12])